version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=fdgjfdkfgo;gfjfjykdfg.gfo;dafhgf;lgfjkgfklghl;
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=aicontdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - ALLOWED_HOST=*
      - EMAIL_PASS=obwjxtqenmfzjzpl
      - EMAIL_HOST_USER=chubiyojoakoji@gmail.com
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
            - 5432:5432
    environment:
      - POSTGRES_DB=aicontdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
