# Generated by Django 4.1.1 on 2023-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_read_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
